/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LokalRouteImport } from './routes/lokal'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as ShareRouteImport } from './routes/share'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAkquiseRouteImport } from './routes/_authenticated/akquise'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedArenaRouteImport } from './routes/_authenticated/arena'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedBewertungenRouteImport } from './routes/_authenticated/bewertungen'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBoostRouteImport } from './routes/_authenticated/boost'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedCeoRouteImport } from './routes/_authenticated/ceo'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedEarnRouteImport } from './routes/_authenticated/earn'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated/files'
import { Route as AuthenticatedHeuteRouteImport } from './routes/_authenticated/heute'
import { Route as AuthenticatedIdentityRouteImport } from './routes/_authenticated/identity'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedKundenRouteImport } from './routes/_authenticated/kunden'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedMissionsRouteImport } from './routes/_authenticated/missions'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTradingRouteImport } from './routes/_authenticated/trading'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedWebsiteRouteImport } from './routes/_authenticated/website'
import { Route as AuthenticatedX402RouteImport } from './routes/_authenticated/x402'
import { Route as ApiCeoRouteImport } from './routes/api/ceo'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as EmbedPostIdRouteImport } from './routes/embed.$postId'
import { Route as ForFunnelRouteImport } from './routes/for.$funnel'
import { Route as MShareSlugRouteImport } from './routes/m.$shareSlug'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as RRunIdRouteImport } from './routes/r.$runId'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as TbShareSlugRouteImport } from './routes/tb.$shareSlug'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as VPostIdRouteImport } from './routes/v.$postId'
import { Route as WShareSlugRouteImport } from './routes/w.$shareSlug'
import { Route as AuthenticatedMissionsIdRouteImport } from './routes/_authenticated/missions.$id'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiBillingFoundingSeatRouteImport } from './routes/api/billing/founding-seat'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiPublicGreeterRouteImport } from './routes/api/public/greeter'
import { Route as ApiWorkersTickRouteImport } from './routes/api/workers/tick'
import { Route as OauthMailboxReturnRouteImport } from './routes/oauth/mailbox.return'
import { Route as OauthSocialReturnRouteImport } from './routes/oauth/social.return'
import { Route as RReviewTokenRouteImport } from './routes/r.review.$token'
import { Route as ApiOauthSocialCallbackRouteImport } from './routes/api/oauth/social/callback'
import { Route as ApiOauthSocialStartRouteImport } from './routes/api/oauth/social/start'
import { Route as ApiPublicX402IndexRouteImport } from './routes/api/public/x402/index'
import { Route as ApiPublicX402AstroReadingRouteImport } from './routes/api/public/x402/astro-reading'
import { Route as ApiPublicX402CompanyBriefRouteImport } from './routes/api/public/x402/company-brief'
import { Route as ApiPublicX402GenesisPassportRouteImport } from './routes/api/public/x402/genesis-passport'
import { Route as ApiPublicX402ImagebookPageRouteImport } from './routes/api/public/x402/imagebook-page'
import { Route as ApiPublicX402LeadEnrichRouteImport } from './routes/api/public/x402/lead-enrich'
import { Route as ApiPublicX402MarketSnapshotRouteImport } from './routes/api/public/x402/market-snapshot'
import { Route as ApiPublicX402OutreachDraftRouteImport } from './routes/api/public/x402/outreach-draft'
import { Route as ApiPublicX402PropertyValuationRouteImport } from './routes/api/public/x402/property-valuation'
import { Route as ApiPublicX402QuantSignalRouteImport } from './routes/api/public/x402/quant-signal'
import { Route as ApiPublicX402WebsiteCopyRouteImport } from './routes/api/public/x402/website-copy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LokalRoute = LokalRouteImport.update({
  id: '/lokal',
  path: '/lokal',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAkquiseRoute = AuthenticatedAkquiseRouteImport.update({
  id: '/akquise',
  path: '/akquise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArenaRoute = AuthenticatedArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBewertungenRoute =
  AuthenticatedBewertungenRouteImport.update({
    id: '/bewertungen',
    path: '/bewertungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoostRoute = AuthenticatedBoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCeoRoute = AuthenticatedCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarnRoute = AuthenticatedEarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHeuteRoute = AuthenticatedHeuteRouteImport.update({
  id: '/heute',
  path: '/heute',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdentityRoute = AuthenticatedIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKundenRoute = AuthenticatedKundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissionsRoute = AuthenticatedMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradingRoute = AuthenticatedTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebsiteRoute = AuthenticatedWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedX402Route = AuthenticatedX402RouteImport.update({
  id: '/x402',
  path: '/x402',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCeoRoute = ApiCeoRouteImport.update({
  id: '/api/ceo',
  path: '/api/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedPostIdRoute = EmbedPostIdRouteImport.update({
  id: '/embed/$postId',
  path: '/embed/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForFunnelRoute = ForFunnelRouteImport.update({
  id: '/for/$funnel',
  path: '/for/$funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const MShareSlugRoute = MShareSlugRouteImport.update({
  id: '/m/$shareSlug',
  path: '/m/$shareSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const RRunIdRoute = RRunIdRouteImport.update({
  id: '/r/$runId',
  path: '/r/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TbShareSlugRoute = TbShareSlugRouteImport.update({
  id: '/tb/$shareSlug',
  path: '/tb/$shareSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const VPostIdRoute = VPostIdRouteImport.update({
  id: '/v/$postId',
  path: '/v/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const WShareSlugRoute = WShareSlugRouteImport.update({
  id: '/w/$shareSlug',
  path: '/w/$shareSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMissionsIdRoute = AuthenticatedMissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMissionsRoute,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingFoundingSeatRoute = ApiBillingFoundingSeatRouteImport.update({
  id: '/api/billing/founding-seat',
  path: '/api/billing/founding-seat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGreeterRoute = ApiPublicGreeterRouteImport.update({
  id: '/api/public/greeter',
  path: '/api/public/greeter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkersTickRoute = ApiWorkersTickRouteImport.update({
  id: '/api/workers/tick',
  path: '/api/workers/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthMailboxReturnRoute = OauthMailboxReturnRouteImport.update({
  id: '/oauth/mailbox/return',
  path: '/oauth/mailbox/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthSocialReturnRoute = OauthSocialReturnRouteImport.update({
  id: '/oauth/social/return',
  path: '/oauth/social/return',
  getParentRoute: () => rootRouteImport,
} as any)
const RReviewTokenRoute = RReviewTokenRouteImport.update({
  id: '/r/review/$token',
  path: '/r/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthSocialCallbackRoute = ApiOauthSocialCallbackRouteImport.update({
  id: '/api/oauth/social/callback',
  path: '/api/oauth/social/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthSocialStartRoute = ApiOauthSocialStartRouteImport.update({
  id: '/api/oauth/social/start',
  path: '/api/oauth/social/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicX402IndexRoute = ApiPublicX402IndexRouteImport.update({
  id: '/api/public/x402/',
  path: '/api/public/x402/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicX402AstroReadingRoute =
  ApiPublicX402AstroReadingRouteImport.update({
    id: '/api/public/x402/astro-reading',
    path: '/api/public/x402/astro-reading',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicX402CompanyBriefRoute =
  ApiPublicX402CompanyBriefRouteImport.update({
    id: '/api/public/x402/company-brief',
    path: '/api/public/x402/company-brief',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicX402GenesisPassportRoute =
  ApiPublicX402GenesisPassportRouteImport.update({
    id: '/api/public/x402/genesis-passport',
    path: '/api/public/x402/genesis-passport',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicX402ImagebookPageRoute =
  ApiPublicX402ImagebookPageRouteImport.update({
    id: '/api/public/x402/imagebook-page',
    path: '/api/public/x402/imagebook-page',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicX402LeadEnrichRoute = ApiPublicX402LeadEnrichRouteImport.update({
  id: '/api/public/x402/lead-enrich',
  path: '/api/public/x402/lead-enrich',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicX402MarketSnapshotRoute =
  ApiPublicX402MarketSnapshotRouteImport.update({
    id: '/api/public/x402/market-snapshot',
    path: '/api/public/x402/market-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicX402OutreachDraftRoute =
  ApiPublicX402OutreachDraftRouteImport.update({
    id: '/api/public/x402/outreach-draft',
    path: '/api/public/x402/outreach-draft',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicX402PropertyValuationRoute =
  ApiPublicX402PropertyValuationRouteImport.update({
    id: '/api/public/x402/property-valuation',
    path: '/api/public/x402/property-valuation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicX402QuantSignalRoute =
  ApiPublicX402QuantSignalRouteImport.update({
    id: '/api/public/x402/quant-signal',
    path: '/api/public/x402/quant-signal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicX402WebsiteCopyRoute =
  ApiPublicX402WebsiteCopyRouteImport.update({
    id: '/api/public/x402/website-copy',
    path: '/api/public/x402/website-copy',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/grants': typeof GrantsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/lokal': typeof LokalRoute
  '/pitch': typeof PitchRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/share': typeof ShareRoute
  '/terms': typeof TermsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/akquise': typeof AuthenticatedAkquiseRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/bewertungen': typeof AuthenticatedBewertungenRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/boost': typeof AuthenticatedBoostRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/earn': typeof AuthenticatedEarnRoute
  '/files': typeof AuthenticatedFilesRoute
  '/heute': typeof AuthenticatedHeuteRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/kunden': typeof AuthenticatedKundenRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/missions': typeof AuthenticatedMissionsRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/report': typeof AuthenticatedReportRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/trading': typeof AuthenticatedTradingRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/website': typeof AuthenticatedWebsiteRoute
  '/x402': typeof AuthenticatedX402Route
  '/api/ceo': typeof ApiCeoRoute
  '/b/$slug': typeof BSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/embed/$postId': typeof EmbedPostIdRoute
  '/for/$funnel': typeof ForFunnelRoute
  '/m/$shareSlug': typeof MShareSlugRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/r/$runId': typeof RRunIdRoute
  '/s/$slug': typeof SSlugRoute
  '/tb/$shareSlug': typeof TbShareSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/v/$postId': typeof VPostIdRoute
  '/w/$shareSlug': typeof WShareSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/missions/$id': typeof AuthenticatedMissionsIdRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/founding-seat': typeof ApiBillingFoundingSeatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/public/greeter': typeof ApiPublicGreeterRoute
  '/api/workers/tick': typeof ApiWorkersTickRoute
  '/oauth/mailbox/return': typeof OauthMailboxReturnRoute
  '/oauth/social/return': typeof OauthSocialReturnRoute
  '/r/review/$token': typeof RReviewTokenRoute
  '/api/oauth/social/callback': typeof ApiOauthSocialCallbackRoute
  '/api/oauth/social/start': typeof ApiOauthSocialStartRoute
  '/api/public/x402/astro-reading': typeof ApiPublicX402AstroReadingRoute
  '/api/public/x402/company-brief': typeof ApiPublicX402CompanyBriefRoute
  '/api/public/x402/genesis-passport': typeof ApiPublicX402GenesisPassportRoute
  '/api/public/x402/imagebook-page': typeof ApiPublicX402ImagebookPageRoute
  '/api/public/x402/lead-enrich': typeof ApiPublicX402LeadEnrichRoute
  '/api/public/x402/market-snapshot': typeof ApiPublicX402MarketSnapshotRoute
  '/api/public/x402/outreach-draft': typeof ApiPublicX402OutreachDraftRoute
  '/api/public/x402/property-valuation': typeof ApiPublicX402PropertyValuationRoute
  '/api/public/x402/quant-signal': typeof ApiPublicX402QuantSignalRoute
  '/api/public/x402/website-copy': typeof ApiPublicX402WebsiteCopyRoute
  '/api/public/x402/': typeof ApiPublicX402IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/grants': typeof GrantsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/lokal': typeof LokalRoute
  '/pitch': typeof PitchRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/share': typeof ShareRoute
  '/terms': typeof TermsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/akquise': typeof AuthenticatedAkquiseRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/bewertungen': typeof AuthenticatedBewertungenRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/boost': typeof AuthenticatedBoostRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/earn': typeof AuthenticatedEarnRoute
  '/files': typeof AuthenticatedFilesRoute
  '/heute': typeof AuthenticatedHeuteRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/kunden': typeof AuthenticatedKundenRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/missions': typeof AuthenticatedMissionsRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/report': typeof AuthenticatedReportRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/trading': typeof AuthenticatedTradingRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/website': typeof AuthenticatedWebsiteRoute
  '/x402': typeof AuthenticatedX402Route
  '/api/ceo': typeof ApiCeoRoute
  '/b/$slug': typeof BSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/embed/$postId': typeof EmbedPostIdRoute
  '/for/$funnel': typeof ForFunnelRoute
  '/m/$shareSlug': typeof MShareSlugRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/r/$runId': typeof RRunIdRoute
  '/s/$slug': typeof SSlugRoute
  '/tb/$shareSlug': typeof TbShareSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/v/$postId': typeof VPostIdRoute
  '/w/$shareSlug': typeof WShareSlugRoute
  '/blog': typeof BlogIndexRoute
  '/missions/$id': typeof AuthenticatedMissionsIdRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/founding-seat': typeof ApiBillingFoundingSeatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/public/greeter': typeof ApiPublicGreeterRoute
  '/api/workers/tick': typeof ApiWorkersTickRoute
  '/oauth/mailbox/return': typeof OauthMailboxReturnRoute
  '/oauth/social/return': typeof OauthSocialReturnRoute
  '/r/review/$token': typeof RReviewTokenRoute
  '/api/oauth/social/callback': typeof ApiOauthSocialCallbackRoute
  '/api/oauth/social/start': typeof ApiOauthSocialStartRoute
  '/api/public/x402/astro-reading': typeof ApiPublicX402AstroReadingRoute
  '/api/public/x402/company-brief': typeof ApiPublicX402CompanyBriefRoute
  '/api/public/x402/genesis-passport': typeof ApiPublicX402GenesisPassportRoute
  '/api/public/x402/imagebook-page': typeof ApiPublicX402ImagebookPageRoute
  '/api/public/x402/lead-enrich': typeof ApiPublicX402LeadEnrichRoute
  '/api/public/x402/market-snapshot': typeof ApiPublicX402MarketSnapshotRoute
  '/api/public/x402/outreach-draft': typeof ApiPublicX402OutreachDraftRoute
  '/api/public/x402/property-valuation': typeof ApiPublicX402PropertyValuationRoute
  '/api/public/x402/quant-signal': typeof ApiPublicX402QuantSignalRoute
  '/api/public/x402/website-copy': typeof ApiPublicX402WebsiteCopyRoute
  '/api/public/x402': typeof ApiPublicX402IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access': typeof AccessRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/grants': typeof GrantsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/lokal': typeof LokalRoute
  '/pitch': typeof PitchRoute
  '/privacy': typeof PrivacyRoute
  '/proof': typeof ProofRoute
  '/share': typeof ShareRoute
  '/terms': typeof TermsRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/akquise': typeof AuthenticatedAkquiseRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/arena': typeof AuthenticatedArenaRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/bewertungen': typeof AuthenticatedBewertungenRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/boost': typeof AuthenticatedBoostRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRoute
  '/_authenticated/ceo': typeof AuthenticatedCeoRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/earn': typeof AuthenticatedEarnRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/heute': typeof AuthenticatedHeuteRoute
  '/_authenticated/identity': typeof AuthenticatedIdentityRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/kunden': typeof AuthenticatedKundenRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/missions': typeof AuthenticatedMissionsRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/trading': typeof AuthenticatedTradingRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/website': typeof AuthenticatedWebsiteRoute
  '/_authenticated/x402': typeof AuthenticatedX402Route
  '/api/ceo': typeof ApiCeoRoute
  '/b/$slug': typeof BSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/embed/$postId': typeof EmbedPostIdRoute
  '/for/$funnel': typeof ForFunnelRoute
  '/m/$shareSlug': typeof MShareSlugRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/r/$runId': typeof RRunIdRoute
  '/s/$slug': typeof SSlugRoute
  '/tb/$shareSlug': typeof TbShareSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/v/$postId': typeof VPostIdRoute
  '/w/$shareSlug': typeof WShareSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/missions/$id': typeof AuthenticatedMissionsIdRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/founding-seat': typeof ApiBillingFoundingSeatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/public/greeter': typeof ApiPublicGreeterRoute
  '/api/workers/tick': typeof ApiWorkersTickRoute
  '/oauth/mailbox/return': typeof OauthMailboxReturnRoute
  '/oauth/social/return': typeof OauthSocialReturnRoute
  '/r/review/$token': typeof RReviewTokenRoute
  '/api/oauth/social/callback': typeof ApiOauthSocialCallbackRoute
  '/api/oauth/social/start': typeof ApiOauthSocialStartRoute
  '/api/public/x402/astro-reading': typeof ApiPublicX402AstroReadingRoute
  '/api/public/x402/company-brief': typeof ApiPublicX402CompanyBriefRoute
  '/api/public/x402/genesis-passport': typeof ApiPublicX402GenesisPassportRoute
  '/api/public/x402/imagebook-page': typeof ApiPublicX402ImagebookPageRoute
  '/api/public/x402/lead-enrich': typeof ApiPublicX402LeadEnrichRoute
  '/api/public/x402/market-snapshot': typeof ApiPublicX402MarketSnapshotRoute
  '/api/public/x402/outreach-draft': typeof ApiPublicX402OutreachDraftRoute
  '/api/public/x402/property-valuation': typeof ApiPublicX402PropertyValuationRoute
  '/api/public/x402/quant-signal': typeof ApiPublicX402QuantSignalRoute
  '/api/public/x402/website-copy': typeof ApiPublicX402WebsiteCopyRoute
  '/api/public/x402/': typeof ApiPublicX402IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/auth'
    | '/cookies'
    | '/faq'
    | '/grants'
    | '/leaderboard'
    | '/live'
    | '/lokal'
    | '/pitch'
    | '/privacy'
    | '/proof'
    | '/share'
    | '/terms'
    | '/agents'
    | '/akquise'
    | '/analytics'
    | '/arena'
    | '/automation'
    | '/bewertungen'
    | '/billing'
    | '/boost'
    | '/business'
    | '/ceo'
    | '/channels'
    | '/community'
    | '/connect'
    | '/console'
    | '/customers'
    | '/earn'
    | '/files'
    | '/heute'
    | '/identity'
    | '/jobs'
    | '/knowledge'
    | '/kunden'
    | '/marketing'
    | '/marketplace'
    | '/missions'
    | '/onboarding'
    | '/products'
    | '/report'
    | '/sales'
    | '/settings'
    | '/social'
    | '/tasks'
    | '/trading'
    | '/wallet'
    | '/website'
    | '/x402'
    | '/api/ceo'
    | '/b/$slug'
    | '/blog/$slug'
    | '/company/$slug'
    | '/embed/$postId'
    | '/for/$funnel'
    | '/m/$shareSlug'
    | '/oauth/consent'
    | '/r/$runId'
    | '/s/$slug'
    | '/tb/$shareSlug'
    | '/u/$handle'
    | '/v/$postId'
    | '/w/$shareSlug'
    | '/blog/'
    | '/missions/$id'
    | '/api/billing/checkout'
    | '/api/billing/founding-seat'
    | '/api/billing/webhook'
    | '/api/public/greeter'
    | '/api/workers/tick'
    | '/oauth/mailbox/return'
    | '/oauth/social/return'
    | '/r/review/$token'
    | '/api/oauth/social/callback'
    | '/api/oauth/social/start'
    | '/api/public/x402/astro-reading'
    | '/api/public/x402/company-brief'
    | '/api/public/x402/genesis-passport'
    | '/api/public/x402/imagebook-page'
    | '/api/public/x402/lead-enrich'
    | '/api/public/x402/market-snapshot'
    | '/api/public/x402/outreach-draft'
    | '/api/public/x402/property-valuation'
    | '/api/public/x402/quant-signal'
    | '/api/public/x402/website-copy'
    | '/api/public/x402/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/auth'
    | '/cookies'
    | '/faq'
    | '/grants'
    | '/leaderboard'
    | '/live'
    | '/lokal'
    | '/pitch'
    | '/privacy'
    | '/proof'
    | '/share'
    | '/terms'
    | '/agents'
    | '/akquise'
    | '/analytics'
    | '/arena'
    | '/automation'
    | '/bewertungen'
    | '/billing'
    | '/boost'
    | '/business'
    | '/ceo'
    | '/channels'
    | '/community'
    | '/connect'
    | '/console'
    | '/customers'
    | '/earn'
    | '/files'
    | '/heute'
    | '/identity'
    | '/jobs'
    | '/knowledge'
    | '/kunden'
    | '/marketing'
    | '/marketplace'
    | '/missions'
    | '/onboarding'
    | '/products'
    | '/report'
    | '/sales'
    | '/settings'
    | '/social'
    | '/tasks'
    | '/trading'
    | '/wallet'
    | '/website'
    | '/x402'
    | '/api/ceo'
    | '/b/$slug'
    | '/blog/$slug'
    | '/company/$slug'
    | '/embed/$postId'
    | '/for/$funnel'
    | '/m/$shareSlug'
    | '/oauth/consent'
    | '/r/$runId'
    | '/s/$slug'
    | '/tb/$shareSlug'
    | '/u/$handle'
    | '/v/$postId'
    | '/w/$shareSlug'
    | '/blog'
    | '/missions/$id'
    | '/api/billing/checkout'
    | '/api/billing/founding-seat'
    | '/api/billing/webhook'
    | '/api/public/greeter'
    | '/api/workers/tick'
    | '/oauth/mailbox/return'
    | '/oauth/social/return'
    | '/r/review/$token'
    | '/api/oauth/social/callback'
    | '/api/oauth/social/start'
    | '/api/public/x402/astro-reading'
    | '/api/public/x402/company-brief'
    | '/api/public/x402/genesis-passport'
    | '/api/public/x402/imagebook-page'
    | '/api/public/x402/lead-enrich'
    | '/api/public/x402/market-snapshot'
    | '/api/public/x402/outreach-draft'
    | '/api/public/x402/property-valuation'
    | '/api/public/x402/quant-signal'
    | '/api/public/x402/website-copy'
    | '/api/public/x402'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access'
    | '/auth'
    | '/cookies'
    | '/faq'
    | '/grants'
    | '/leaderboard'
    | '/live'
    | '/lokal'
    | '/pitch'
    | '/privacy'
    | '/proof'
    | '/share'
    | '/terms'
    | '/_authenticated/agents'
    | '/_authenticated/akquise'
    | '/_authenticated/analytics'
    | '/_authenticated/arena'
    | '/_authenticated/automation'
    | '/_authenticated/bewertungen'
    | '/_authenticated/billing'
    | '/_authenticated/boost'
    | '/_authenticated/business'
    | '/_authenticated/ceo'
    | '/_authenticated/channels'
    | '/_authenticated/community'
    | '/_authenticated/connect'
    | '/_authenticated/console'
    | '/_authenticated/customers'
    | '/_authenticated/earn'
    | '/_authenticated/files'
    | '/_authenticated/heute'
    | '/_authenticated/identity'
    | '/_authenticated/jobs'
    | '/_authenticated/knowledge'
    | '/_authenticated/kunden'
    | '/_authenticated/marketing'
    | '/_authenticated/marketplace'
    | '/_authenticated/missions'
    | '/_authenticated/onboarding'
    | '/_authenticated/products'
    | '/_authenticated/report'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/social'
    | '/_authenticated/tasks'
    | '/_authenticated/trading'
    | '/_authenticated/wallet'
    | '/_authenticated/website'
    | '/_authenticated/x402'
    | '/api/ceo'
    | '/b/$slug'
    | '/blog/$slug'
    | '/company/$slug'
    | '/embed/$postId'
    | '/for/$funnel'
    | '/m/$shareSlug'
    | '/oauth/consent'
    | '/r/$runId'
    | '/s/$slug'
    | '/tb/$shareSlug'
    | '/u/$handle'
    | '/v/$postId'
    | '/w/$shareSlug'
    | '/blog/'
    | '/_authenticated/missions/$id'
    | '/api/billing/checkout'
    | '/api/billing/founding-seat'
    | '/api/billing/webhook'
    | '/api/public/greeter'
    | '/api/workers/tick'
    | '/oauth/mailbox/return'
    | '/oauth/social/return'
    | '/r/review/$token'
    | '/api/oauth/social/callback'
    | '/api/oauth/social/start'
    | '/api/public/x402/astro-reading'
    | '/api/public/x402/company-brief'
    | '/api/public/x402/genesis-passport'
    | '/api/public/x402/imagebook-page'
    | '/api/public/x402/lead-enrich'
    | '/api/public/x402/market-snapshot'
    | '/api/public/x402/outreach-draft'
    | '/api/public/x402/property-valuation'
    | '/api/public/x402/quant-signal'
    | '/api/public/x402/website-copy'
    | '/api/public/x402/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessRoute: typeof AccessRoute
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  GrantsRoute: typeof GrantsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveRoute: typeof LiveRoute
  LokalRoute: typeof LokalRoute
  PitchRoute: typeof PitchRoute
  PrivacyRoute: typeof PrivacyRoute
  ProofRoute: typeof ProofRoute
  ShareRoute: typeof ShareRoute
  TermsRoute: typeof TermsRoute
  ApiCeoRoute: typeof ApiCeoRoute
  BSlugRoute: typeof BSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CompanySlugRoute: typeof CompanySlugRoute
  EmbedPostIdRoute: typeof EmbedPostIdRoute
  ForFunnelRoute: typeof ForFunnelRoute
  MShareSlugRoute: typeof MShareSlugRoute
  OauthConsentRoute: typeof OauthConsentRoute
  RRunIdRoute: typeof RRunIdRoute
  SSlugRoute: typeof SSlugRoute
  TbShareSlugRoute: typeof TbShareSlugRoute
  UHandleRoute: typeof UHandleRoute
  VPostIdRoute: typeof VPostIdRoute
  WShareSlugRoute: typeof WShareSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingFoundingSeatRoute: typeof ApiBillingFoundingSeatRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiPublicGreeterRoute: typeof ApiPublicGreeterRoute
  ApiWorkersTickRoute: typeof ApiWorkersTickRoute
  OauthMailboxReturnRoute: typeof OauthMailboxReturnRoute
  OauthSocialReturnRoute: typeof OauthSocialReturnRoute
  RReviewTokenRoute: typeof RReviewTokenRoute
  ApiOauthSocialCallbackRoute: typeof ApiOauthSocialCallbackRoute
  ApiOauthSocialStartRoute: typeof ApiOauthSocialStartRoute
  ApiPublicX402AstroReadingRoute: typeof ApiPublicX402AstroReadingRoute
  ApiPublicX402CompanyBriefRoute: typeof ApiPublicX402CompanyBriefRoute
  ApiPublicX402GenesisPassportRoute: typeof ApiPublicX402GenesisPassportRoute
  ApiPublicX402ImagebookPageRoute: typeof ApiPublicX402ImagebookPageRoute
  ApiPublicX402LeadEnrichRoute: typeof ApiPublicX402LeadEnrichRoute
  ApiPublicX402MarketSnapshotRoute: typeof ApiPublicX402MarketSnapshotRoute
  ApiPublicX402OutreachDraftRoute: typeof ApiPublicX402OutreachDraftRoute
  ApiPublicX402PropertyValuationRoute: typeof ApiPublicX402PropertyValuationRoute
  ApiPublicX402QuantSignalRoute: typeof ApiPublicX402QuantSignalRoute
  ApiPublicX402WebsiteCopyRoute: typeof ApiPublicX402WebsiteCopyRoute
  ApiPublicX402IndexRoute: typeof ApiPublicX402IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokal': {
      id: '/lokal'
      path: '/lokal'
      fullPath: '/lokal'
      preLoaderRoute: typeof LokalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akquise': {
      id: '/_authenticated/akquise'
      path: '/akquise'
      fullPath: '/akquise'
      preLoaderRoute: typeof AuthenticatedAkquiseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arena': {
      id: '/_authenticated/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof AuthenticatedArenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bewertungen': {
      id: '/_authenticated/bewertungen'
      path: '/bewertungen'
      fullPath: '/bewertungen'
      preLoaderRoute: typeof AuthenticatedBewertungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boost': {
      id: '/_authenticated/boost'
      path: '/boost'
      fullPath: '/boost'
      preLoaderRoute: typeof AuthenticatedBoostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ceo': {
      id: '/_authenticated/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof AuthenticatedCeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earn': {
      id: '/_authenticated/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof AuthenticatedEarnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/heute': {
      id: '/_authenticated/heute'
      path: '/heute'
      fullPath: '/heute'
      preLoaderRoute: typeof AuthenticatedHeuteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identity': {
      id: '/_authenticated/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof AuthenticatedIdentityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunden': {
      id: '/_authenticated/kunden'
      path: '/kunden'
      fullPath: '/kunden'
      preLoaderRoute: typeof AuthenticatedKundenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions': {
      id: '/_authenticated/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AuthenticatedMissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trading': {
      id: '/_authenticated/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof AuthenticatedTradingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website': {
      id: '/_authenticated/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AuthenticatedWebsiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/x402': {
      id: '/_authenticated/x402'
      path: '/x402'
      fullPath: '/x402'
      preLoaderRoute: typeof AuthenticatedX402RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ceo': {
      id: '/api/ceo'
      path: '/api/ceo'
      fullPath: '/api/ceo'
      preLoaderRoute: typeof ApiCeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$postId': {
      id: '/embed/$postId'
      path: '/embed/$postId'
      fullPath: '/embed/$postId'
      preLoaderRoute: typeof EmbedPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/$funnel': {
      id: '/for/$funnel'
      path: '/for/$funnel'
      fullPath: '/for/$funnel'
      preLoaderRoute: typeof ForFunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$shareSlug': {
      id: '/m/$shareSlug'
      path: '/m/$shareSlug'
      fullPath: '/m/$shareSlug'
      preLoaderRoute: typeof MShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$runId': {
      id: '/r/$runId'
      path: '/r/$runId'
      fullPath: '/r/$runId'
      preLoaderRoute: typeof RRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tb/$shareSlug': {
      id: '/tb/$shareSlug'
      path: '/tb/$shareSlug'
      fullPath: '/tb/$shareSlug'
      preLoaderRoute: typeof TbShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$postId': {
      id: '/v/$postId'
      path: '/v/$postId'
      fullPath: '/v/$postId'
      preLoaderRoute: typeof VPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$shareSlug': {
      id: '/w/$shareSlug'
      path: '/w/$shareSlug'
      fullPath: '/w/$shareSlug'
      preLoaderRoute: typeof WShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/missions/$id': {
      id: '/_authenticated/missions/$id'
      path: '/$id'
      fullPath: '/missions/$id'
      preLoaderRoute: typeof AuthenticatedMissionsIdRouteImport
      parentRoute: typeof AuthenticatedMissionsRoute
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/founding-seat': {
      id: '/api/billing/founding-seat'
      path: '/api/billing/founding-seat'
      fullPath: '/api/billing/founding-seat'
      preLoaderRoute: typeof ApiBillingFoundingSeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/greeter': {
      id: '/api/public/greeter'
      path: '/api/public/greeter'
      fullPath: '/api/public/greeter'
      preLoaderRoute: typeof ApiPublicGreeterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/tick': {
      id: '/api/workers/tick'
      path: '/api/workers/tick'
      fullPath: '/api/workers/tick'
      preLoaderRoute: typeof ApiWorkersTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/mailbox/return': {
      id: '/oauth/mailbox/return'
      path: '/oauth/mailbox/return'
      fullPath: '/oauth/mailbox/return'
      preLoaderRoute: typeof OauthMailboxReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/social/return': {
      id: '/oauth/social/return'
      path: '/oauth/social/return'
      fullPath: '/oauth/social/return'
      preLoaderRoute: typeof OauthSocialReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/review/$token': {
      id: '/r/review/$token'
      path: '/r/review/$token'
      fullPath: '/r/review/$token'
      preLoaderRoute: typeof RReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/social/callback': {
      id: '/api/oauth/social/callback'
      path: '/api/oauth/social/callback'
      fullPath: '/api/oauth/social/callback'
      preLoaderRoute: typeof ApiOauthSocialCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/social/start': {
      id: '/api/oauth/social/start'
      path: '/api/oauth/social/start'
      fullPath: '/api/oauth/social/start'
      preLoaderRoute: typeof ApiOauthSocialStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/': {
      id: '/api/public/x402/'
      path: '/api/public/x402'
      fullPath: '/api/public/x402/'
      preLoaderRoute: typeof ApiPublicX402IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/astro-reading': {
      id: '/api/public/x402/astro-reading'
      path: '/api/public/x402/astro-reading'
      fullPath: '/api/public/x402/astro-reading'
      preLoaderRoute: typeof ApiPublicX402AstroReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/company-brief': {
      id: '/api/public/x402/company-brief'
      path: '/api/public/x402/company-brief'
      fullPath: '/api/public/x402/company-brief'
      preLoaderRoute: typeof ApiPublicX402CompanyBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/genesis-passport': {
      id: '/api/public/x402/genesis-passport'
      path: '/api/public/x402/genesis-passport'
      fullPath: '/api/public/x402/genesis-passport'
      preLoaderRoute: typeof ApiPublicX402GenesisPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/imagebook-page': {
      id: '/api/public/x402/imagebook-page'
      path: '/api/public/x402/imagebook-page'
      fullPath: '/api/public/x402/imagebook-page'
      preLoaderRoute: typeof ApiPublicX402ImagebookPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/lead-enrich': {
      id: '/api/public/x402/lead-enrich'
      path: '/api/public/x402/lead-enrich'
      fullPath: '/api/public/x402/lead-enrich'
      preLoaderRoute: typeof ApiPublicX402LeadEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/market-snapshot': {
      id: '/api/public/x402/market-snapshot'
      path: '/api/public/x402/market-snapshot'
      fullPath: '/api/public/x402/market-snapshot'
      preLoaderRoute: typeof ApiPublicX402MarketSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/outreach-draft': {
      id: '/api/public/x402/outreach-draft'
      path: '/api/public/x402/outreach-draft'
      fullPath: '/api/public/x402/outreach-draft'
      preLoaderRoute: typeof ApiPublicX402OutreachDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/property-valuation': {
      id: '/api/public/x402/property-valuation'
      path: '/api/public/x402/property-valuation'
      fullPath: '/api/public/x402/property-valuation'
      preLoaderRoute: typeof ApiPublicX402PropertyValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/quant-signal': {
      id: '/api/public/x402/quant-signal'
      path: '/api/public/x402/quant-signal'
      fullPath: '/api/public/x402/quant-signal'
      preLoaderRoute: typeof ApiPublicX402QuantSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402/website-copy': {
      id: '/api/public/x402/website-copy'
      path: '/api/public/x402/website-copy'
      fullPath: '/api/public/x402/website-copy'
      preLoaderRoute: typeof ApiPublicX402WebsiteCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMissionsRouteChildren {
  AuthenticatedMissionsIdRoute: typeof AuthenticatedMissionsIdRoute
}

const AuthenticatedMissionsRouteChildren: AuthenticatedMissionsRouteChildren = {
  AuthenticatedMissionsIdRoute: AuthenticatedMissionsIdRoute,
}

const AuthenticatedMissionsRouteWithChildren =
  AuthenticatedMissionsRoute._addFileChildren(
    AuthenticatedMissionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAkquiseRoute: typeof AuthenticatedAkquiseRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedArenaRoute: typeof AuthenticatedArenaRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedBewertungenRoute: typeof AuthenticatedBewertungenRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBoostRoute: typeof AuthenticatedBoostRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRoute
  AuthenticatedCeoRoute: typeof AuthenticatedCeoRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedEarnRoute: typeof AuthenticatedEarnRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedHeuteRoute: typeof AuthenticatedHeuteRoute
  AuthenticatedIdentityRoute: typeof AuthenticatedIdentityRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedKundenRoute: typeof AuthenticatedKundenRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMissionsRoute: typeof AuthenticatedMissionsRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTradingRoute: typeof AuthenticatedTradingRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWebsiteRoute: typeof AuthenticatedWebsiteRoute
  AuthenticatedX402Route: typeof AuthenticatedX402Route
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAkquiseRoute: AuthenticatedAkquiseRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedArenaRoute: AuthenticatedArenaRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedBewertungenRoute: AuthenticatedBewertungenRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBoostRoute: AuthenticatedBoostRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRoute,
  AuthenticatedCeoRoute: AuthenticatedCeoRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedEarnRoute: AuthenticatedEarnRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedHeuteRoute: AuthenticatedHeuteRoute,
  AuthenticatedIdentityRoute: AuthenticatedIdentityRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedKundenRoute: AuthenticatedKundenRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMissionsRoute: AuthenticatedMissionsRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTradingRoute: AuthenticatedTradingRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWebsiteRoute: AuthenticatedWebsiteRoute,
  AuthenticatedX402Route: AuthenticatedX402Route,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessRoute: AccessRoute,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  GrantsRoute: GrantsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveRoute: LiveRoute,
  LokalRoute: LokalRoute,
  PitchRoute: PitchRoute,
  PrivacyRoute: PrivacyRoute,
  ProofRoute: ProofRoute,
  ShareRoute: ShareRoute,
  TermsRoute: TermsRoute,
  ApiCeoRoute: ApiCeoRoute,
  BSlugRoute: BSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  CompanySlugRoute: CompanySlugRoute,
  EmbedPostIdRoute: EmbedPostIdRoute,
  ForFunnelRoute: ForFunnelRoute,
  MShareSlugRoute: MShareSlugRoute,
  OauthConsentRoute: OauthConsentRoute,
  RRunIdRoute: RRunIdRoute,
  SSlugRoute: SSlugRoute,
  TbShareSlugRoute: TbShareSlugRoute,
  UHandleRoute: UHandleRoute,
  VPostIdRoute: VPostIdRoute,
  WShareSlugRoute: WShareSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingFoundingSeatRoute: ApiBillingFoundingSeatRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiPublicGreeterRoute: ApiPublicGreeterRoute,
  ApiWorkersTickRoute: ApiWorkersTickRoute,
  OauthMailboxReturnRoute: OauthMailboxReturnRoute,
  OauthSocialReturnRoute: OauthSocialReturnRoute,
  RReviewTokenRoute: RReviewTokenRoute,
  ApiOauthSocialCallbackRoute: ApiOauthSocialCallbackRoute,
  ApiOauthSocialStartRoute: ApiOauthSocialStartRoute,
  ApiPublicX402AstroReadingRoute: ApiPublicX402AstroReadingRoute,
  ApiPublicX402CompanyBriefRoute: ApiPublicX402CompanyBriefRoute,
  ApiPublicX402GenesisPassportRoute: ApiPublicX402GenesisPassportRoute,
  ApiPublicX402ImagebookPageRoute: ApiPublicX402ImagebookPageRoute,
  ApiPublicX402LeadEnrichRoute: ApiPublicX402LeadEnrichRoute,
  ApiPublicX402MarketSnapshotRoute: ApiPublicX402MarketSnapshotRoute,
  ApiPublicX402OutreachDraftRoute: ApiPublicX402OutreachDraftRoute,
  ApiPublicX402PropertyValuationRoute: ApiPublicX402PropertyValuationRoute,
  ApiPublicX402QuantSignalRoute: ApiPublicX402QuantSignalRoute,
  ApiPublicX402WebsiteCopyRoute: ApiPublicX402WebsiteCopyRoute,
  ApiPublicX402IndexRoute: ApiPublicX402IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
