// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  const SUPABASE_URL =
    process.env["SUPABASE_URL"] || process.env["VITE_SUPABASE_URL"];
  // Prefer classic service_role JWT; also accept new opaque secret keys (sb_secret_…).
  // SUPABASE_SERVICE_ROLE_KEY_SECRET is a common local alias when the main var was
  // accidentally filled with the anon JWT.
  const candidates = [
    process.env["SUPABASE_SERVICE_ROLE_KEY"],
    process.env["SUPABASE_SECRET_KEY"],
    process.env["SUPABASE_SERVICE_ROLE_KEY_SECRET"],
  ].filter((v): v is string => Boolean(v && v.trim()));

  let SUPABASE_SERVICE_ROLE_KEY = candidates[0];
  for (const key of candidates) {
    if (key.startsWith("sb_secret_")) {
      SUPABASE_SERVICE_ROLE_KEY = key;
      break;
    }
    if (key.split(".").length === 3) {
      try {
        const payload = key.split(".")[1]!;
        const pad = "=".repeat((4 - (payload.length % 4)) % 4);
        const claim = JSON.parse(
          Buffer.from(payload.replace(/-/g, "+").replace(/_/g, "/") + pad, "base64").toString(
            "utf8",
          ),
        ) as { role?: string };
        if (claim.role === "service_role") {
          SUPABASE_SERVICE_ROLE_KEY = key;
          break;
        }
      } catch {
        /* keep scanning */
      }
    }
  }

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY
        ? ["SUPABASE_SERVICE_ROLE_KEY (or SUPABASE_SECRET_KEY)"]
        : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Add the service_role / secret key from Supabase → Project Settings → API Keys.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Fail loudly if someone pasted the anon JWT into SERVICE_ROLE — RLS then
  // makes every admin lookup look like "Company not found".
  if (SUPABASE_SERVICE_ROLE_KEY.split(".").length === 3) {
    try {
      const payload = SUPABASE_SERVICE_ROLE_KEY.split(".")[1]!;
      const pad = "=".repeat((4 - (payload.length % 4)) % 4);
      const claim = JSON.parse(
        Buffer.from(payload.replace(/-/g, "+").replace(/_/g, "/") + pad, "base64").toString(
          "utf8",
        ),
      ) as { role?: string };
      if (claim.role && claim.role !== "service_role") {
        throw new Error(
          `SUPABASE_SERVICE_ROLE_KEY has role "${claim.role}" — use the service_role secret from Supabase → Settings → API, not the anon/publishable key.`,
        );
      }
    } catch (e) {
      if (e instanceof Error && e.message.includes("SUPABASE_SERVICE_ROLE_KEY has role")) throw e;
    }
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
